module.exports = {
	rules: {
		'vue/array-bracket-spacing': [ 'error', 'always', { 'singleValue': true, 'objectsInArrays': true, 'arraysInArrays': true } ],
		'vue/arrow-spacing': [ 'error', { 'before': true, 'after': true } ],
		'vue/attribute-hyphenation': [ 'error', 'always' ],
		'vue/attributes-order': [ 'error', {
			'order': [
				'DEFINITION',
				'LIST_RENDERING',
				'CONDITIONALS',
				'RENDER_MODIFIERS',
				'GLOBAL',
				'UNIQUE',
				'TWO_WAY_BINDING',
				'OTHER_DIRECTIVES',
				'OTHER_ATTR',
				'EVENTS',
				'CONTENT'
			],
			'alphabetical': false
		} ],
		'vue/block-spacing': [ 'error', 'always' ],
		'vue/brace-style': [ 'error', '1tbs', { 'allowSingleLine': true } ],
		'vue/camelcase': [ 'error', { 'properties': 'always', 'ignoreDestructuring': false, 'ignoreImports': false } ],
		'vue/comma-dangle': [ 'error', 'never' ],
		'vue/comment-directive': 'error',
		'vue/component-definition-name-casing': [ 'error', 'PascalCase' ],
		'vue/component-name-in-template-casing': [ 'error', 'PascalCase', { 'registeredComponentsOnly': false } ],
		'vue/component-tags-order': [ 'error', { 'order': [ 'script', 'template', 'style' ] } ],
		'vue/dot-location': [ 'error', 'property' ],
		'vue/eqeqeq': [ 'error', 'smart' ],
		// 'vue/html-closing-bracket-newline': 'off',
		'vue/html-closing-bracket-spacing': [ 'error', { 'startTag': 'never', 'endTag': 'never', 'selfClosingTag': 'never' } ],
		'vue/html-end-tags': 'error',
		'vue/html-indent': [ 'error', 'tab', { 'attribute': 1, 'baseIndent': 1, 'closeBracket': 0, 'alignAttributesVertically': true } ],
		'vue/html-quotes': [ 'error', 'double', { 'avoidEscape': false } ],
		'vue/html-self-closing': [ 'error', { 'html': { 'void': 'never', 'normal': 'never', 'component': 'always' }, 'svg': 'never', 'math': 'never' } ],
		// 'vue/jsx-uses-vars': 'off',
		'vue/key-spacing': [ 'error', { 'mode': 'minimum' } ],
		'vue/keyword-spacing': [ 'error', { 'before': true, 'after': true } ],
		'vue/match-component-file-name': [ 'error', { 'extensions': [ 'vue' ], 'shouldMatchCase': true } ],
		// 'vue/max-attributes-per-line': 'off',
		// 'vue/max-len': 'off',
		'vue/multiline-html-element-content-newline': [ 'error', { 'ignoreWhenEmpty': true, 'ignores': [ 'pre', 'textarea', 'a', 'abbr', 'audio', 'b', 'bdi', 'bdo', 'canvas', 'cite', 'code', 'data', 'del', 'dfn', 'em', 'i', 'iframe', 'ins', 'kbd', 'label', 'map', 'mark', 'noscript', 'object', 'output', 'picture', 'q', 'ruby', 's', 'samp', 'small', 'span', 'strong', 'sub', 'sup', 'svg', 'time', 'u', 'var', 'video' ], 'allowEmptyLines': false } ],
		'vue/mustache-interpolation-spacing': [ 'error', 'always' ],
		'vue/name-property-casing': [ 'error', 'PascalCase' ],
		'vue/no-async-in-computed-properties': 'error',
		// 'vue/no-boolean-default': 'off',
		'vue/no-deprecated-scope-attribute': 'error',
		'vue/no-deprecated-slot-attribute': 'error',
		'vue/no-deprecated-slot-scope-attribute': 'error',
		'vue/no-dupe-keys': 'error',
		'vue/no-duplicate-attributes': [ 'error', { 'allowCoexistClass': true, 'allowCoexistStyle': true } ],
		'vue/no-empty-pattern': 'error',
		'vue/no-irregular-whitespace': [ 'error', { 'skipStrings': false, 'skipComments': false, 'skipRegExps': false, 'skipTemplates': false, 'skipHTMLAttributeValues': false, 'skipHTMLTextContents': false } ],
		'vue/no-multi-spaces': [ 'error', { 'ignoreProperties': false } ],
		'vue/no-parsing-error': [ 'error', {
			'abrupt-closing-of-empty-comment': true,
			'absence-of-digits-in-numeric-character-reference': true,
			'cdata-in-html-content': true,
			'character-reference-outside-unicode-range': true,
			'control-character-in-input-stream': true,
			'control-character-reference': true,
			'eof-before-tag-name': true,
			'eof-in-cdata': true,
			'eof-in-comment': true,
			'eof-in-tag': true,
			'incorrectly-closed-comment': true,
			'incorrectly-opened-comment': true,
			'invalid-first-character-of-tag-name': true,
			'missing-attribute-value': true,
			'missing-end-tag-name': true,
			'missing-semicolon-after-character-reference': true,
			'missing-whitespace-between-attributes': true,
			'nested-comment': true,
			'noncharacter-character-reference': true,
			'noncharacter-in-input-stream': true,
			'null-character-reference': true,
			'surrogate-character-reference': true,
			'surrogate-in-input-stream': true,
			'unexpected-character-in-attribute-name': true,
			'unexpected-character-in-unquoted-attribute-value': true,
			'unexpected-equals-sign-before-attribute-name': true,
			'unexpected-null-character': true,
			'unexpected-question-mark-instead-of-tag-name': true,
			'unexpected-solidus-in-tag': true,
			'unknown-named-character-reference': true,
			'end-tag-with-attributes': true,
			'duplicate-attribute': true,
			'end-tag-with-trailing-solidus': true,
			'non-void-html-element-start-tag-with-trailing-solidus': false,
			'x-invalid-end-tag': true,
			'x-invalid-namespace': true
		} ],
		'vue/no-reserved-component-names': 'error',
		'vue/no-reserved-keys': 'error',
		// 'vue/no-restricted-syntax': 'off',
		'vue/no-shared-component-data': 'error',
		'vue/no-side-effects-in-computed-properties': 'error',
		'vue/no-spaces-around-equal-signs-in-attribute': 'error',
		'vue/no-static-inline-styles': [ 'error', { 'allowBinding': false } ],
		'vue/no-template-key': 'error',
		'vue/no-template-shadow': 'error',
		'vue/no-textarea-mustache': 'error',
		'vue/no-unsupported-features': [ 'error', { 'version': '^2.6.0' } ],
		'vue/no-unused-components': [ 'error', { 'ignoreWhenBindingPresent': true } ],
		'vue/no-unused-vars': 'error',
		'vue/no-use-v-if-with-v-for': [ 'error', { 'allowUsingIterationVar': false } ],
		'vue/no-v-html': 'error',
		'vue/object-curly-spacing': [ 'error', 'always', { 'arraysInObjects': true, 'objectsInObjects': true } ],
		'vue/order-in-components': [ 'error', { 'order': [
			'el',
			'name',
			'parent',
			'functional',
			[ 'delimiters', 'comments' ],
			[ 'components', 'directives', 'filters' ],
			'extends',
			'mixins',
			'inheritAttrs',
			'model',
			[ 'props', 'propsData' ],
			'fetch',
			'asyncData',
			'data',
			'computed',
			'watch',
			'LIFECYCLE_HOOKS',
			'methods',
			'head',
			[ 'template', 'render' ],
			'renderError'
		] } ],
		'vue/padding-line-between-blocks': [ 'error', 'always' ],
		'vue/prop-name-casing': [ 'error', 'camelCase' ],
		'vue/require-component-is': 'error',
		// 'vue/require-default-prop': 'off',
		'vue/require-direct-export': 'error',
		// 'vue/require-name-property': 'off',
		'vue/require-prop-type-constructor': 'error',
		'vue/require-prop-types': 'error',
		'vue/require-render-return': 'error',
		'vue/require-v-for-key': 'error',
		'vue/require-valid-default-prop': 'error',
		'vue/return-in-computed-property': [ 'error', { 'treatUndefinedAsUnspecified': true } ],
		// 'vue/script-indent': 'off',
		// 'vue/singleline-html-element-content-newline': 'off',
		// 'vue/sort-keys': 'off',
		'vue/space-infix-ops': [ 'error', { 'int32Hint': false } ],
		'vue/space-unary-ops': [ 'error', { 'words': true, 'nonwords': false } ],
		// 'vue/static-class-names-order': 'off',
		'vue/this-in-template': [ 'error', 'never' ],
		'vue/use-v-on-exact': 'error',
		'vue/v-bind-style': [ 'error', 'shorthand' ],
		// 'vue/v-on-function-call': 'off',
		'vue/v-on-style': [ 'error', 'shorthand' ],
		'vue/v-slot-style': [ 'error', { 'atComponent': 'shorthand', 'default': 'shorthand', 'named': 'shorthand' } ],
		'vue/valid-template-root': 'error',
		'vue/valid-v-bind': 'error',
		'vue/valid-v-bind-sync': 'error',
		'vue/valid-v-cloak': 'error',
		'vue/valid-v-else-if': 'error',
		'vue/valid-v-else': 'error',
		'vue/valid-v-for': 'error',
		'vue/valid-v-html': 'error',
		'vue/valid-v-if': 'error',
		'vue/valid-v-model': 'error',
		'vue/valid-v-on': 'error',
		'vue/valid-v-once': 'error',
		'vue/valid-v-pre': 'error',
		'vue/valid-v-show': 'error',
		'vue/valid-v-slot': 'error',
		'vue/valid-v-text': 'error'
	}
};